### ISSUE TITLE
你好，请问目前taro-lottie支持微信小程序吗？

### ISSUE THREAD

**Issue by hello-chinese** [zhiqingchen/taro-lottie#2]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by zhiqingchen** [comment]
支持，见readme
